apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: flyway
  name: flyway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flyway
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: flyway
    spec:
      containers:
        - command:
            - sh
            - -c
            - flyway -defaultSchema=employees -baselineOnMigrate=true -connectRetries=60 -url=jdbc:postgresql://db:5432/postgres -user=postgres -password=your_password
          image: flyway/flyway
          name: flyway
          volumeMounts:
            - mountPath: /flyway/sql
              name: flyway-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: flyway-cm0
          name: flyway-cm0
